# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

variables:
- name: Codeql.Enabled
  value: true

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- task: CredScan@3
  inputs:
      outputFormat: 'csv'


- task: UseDotNet@2
  displayName: 'Use dotnet 3.1.x'
  inputs:
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Use dotnet 5.0.x'
  inputs:
    version: 5.0.x

- task: UseDotNet@2
  displayName: 'Use dotnet 6.0.x'
  inputs:
    version: 6.0.x

- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'
  inputs:
    tools: 'bandit'
