$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: frameworkEnvironment
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: environment.yml
description: Environment created from docker and conda