#Copyright (c) Microsoft. All rights reserved.
ScoringConfig:
  experimentset: "experimentset1"
  experiment: "experiment1"
  modelName : "DeepMC"
  scriptSourceDir : "./code/mlcode"
  environmentYAMLFile : "deepmcenvironment.yml"
  environment: "deepmcFrameworkEnvironment"
  entryPoint : "scoredeepmc.py"
  requiredColumns: ["IoT_hs_windspeed"]
  targetColumn: "power_power"
  futureCovariates: ["darksky_ds_windspeed"]
  dateField: "DateTime"
  modelPath : "outputs/experimentset1/experiment1/20230202064548/"
  # Parameters to get predictions
  parameters : {
      "DartsTFT" : {
        "n" : 6
        ,"forecast_horizon" : 24
        ,"verbose" : False
        ,"last_points_only" : False }, 
      "DartsTCN" : {
         "n" : 6
        ,"forecast_horizon" : 24
        ,"verbose" : False
        ,"last_points_only" : False }, 
      "DartsNBeats" : {
        "n" : 6
        ,"forecast_horizon" : 24
        ,"verbose" : False
        ,"last_points_only" : False }, 
      "DeepMC" : {
        "horizon" : 24
        ,"trunc" : 512
        ,"lookback" : 24
        ,"freq" : "60min"
        ,"frequency" : 1
        ,"frequency_duration" : "H"
        ,"predDate" : '2018-10-01 00:00:00s'
      },
      "TFT" : {
        "forecast_horizon" : 24
        ,"freq" : "60min"
        ,"lookback" : 24
        ,"sample_frequency": "H"
        }
    }