trigger:
- none

pool:
  vmImage: 'ubuntu-latest' 

parameters:
#Service connection details
- name: ServiceConnection
  type: string
  default: arm-service-connection
  displayName: Service Connection

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  
    addToPath: true

- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.ServiceConnection }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      python -m pip install -r requirements.txt
      python goliveSetup.py
  displayName: 'Run Go live setup in subscription'
