CREATE TABLE [static].[windturbines] (
    [entitytype]   VARCHAR (50) NULL,
    [manufacturer] VARCHAR (50) NULL,
    [turbine]      VARCHAR (50) NULL,
    [0]            INT          NULL,
    [0 5]          INT          NULL,
    [1]            INT          NULL,
    [1 5]          INT          NULL,
    [2]            INT          NULL,
    [2 5]          INT          NULL,
    [3]            INT          NULL,
    [3 5]          INT          NULL,
    [4]            INT          NULL,
    [4 5]          INT          NULL,
    [5]            INT          NULL,
    [5 5]          INT          NULL,
    [6]            INT          NULL,
    [6 5]          INT          NULL,
    [7]            INT          NULL,
    [7 5]          INT          NULL,
    [8]            INT          NULL,
    [8 5]          INT          NULL,
    [9]            INT          NULL,
    [9 5]          INT          NULL,
    [10]           INT          NULL,
    [10 5]         INT          NULL,
    [11]           INT          NULL,
    [11 5]         INT          NULL,
    [12]           INT          NULL,
    [12 5]         INT          NULL,
    [13]           INT          NULL,
    [13 5]         INT          NULL,
    [14]           INT          NULL,
    [14 5]         INT          NULL,
    [15]           INT          NULL,
    [15 5]         INT          NULL,
    [16]           INT          NULL,
    [16 5]         INT          NULL,
    [17]           INT          NULL,
    [17 5]         INT          NULL,
    [18]           INT          NULL,
    [18 5]         INT          NULL,
    [19]           INT          NULL,
    [19 5]         INT          NULL,
    [20]           INT          NULL,
    [20 5]         INT          NULL,
    [21]           INT          NULL,
    [21 5]         INT          NULL,
    [22]           INT          NULL,
    [22 5]         INT          NULL,
    [23]           INT          NULL,
    [23 5]         INT          NULL,
    [24]           INT          NULL,
    [24 5]         INT          NULL,
    [25]           INT          NULL,
    [25 5]         INT          NULL,
    [26]           INT          NULL,
    [26 5]         INT          NULL,
    [27]           INT          NULL,
    [27 5]         INT          NULL,
    [28]           INT          NULL,
    [28 5]         INT          NULL,
    [29]           INT          NULL,
    [29 5]         INT          NULL,
    [30]           INT          NULL,
    [30 5]         INT          NULL,
    [31]           INT          NULL,
    [31 5]         INT          NULL,
    [32]           INT          NULL,
    [32 5]         INT          NULL,
    [33]           INT          NULL,
    [33 5]         INT          NULL,
    [34]           INT          NULL,
    [34 5]         INT          NULL,
    [35]           INT          NULL
);

